name: 'docker'

on:
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Timestamp
        run: echo "timestamp=$(date '+%Y%m%d_%H%M%S')" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/bboehmke/docker-landing-page:${{env.timestamp}},ghcr.io/bboehmke/docker-landing-page:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}